service: ChatGPTSlackFunctionSample
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - bedrock:*
          Resource: "*"

package:
  patterns:
    - '!.venv/**'
    - '!.env'
    - '!.gitignore'
    - '!.python-version'
    - '!.git/**'

functions:
  app:
    name: ChatGPTSlackFunctionSample-${sls:stage}-app
    handler: app.handler
    runtime: python3.10
    memorySize: 512
    timeout: 900
    url: true
    
resources:
  Resources:
    ChatHistory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChatHistory
        AttributeDefinitions:
          - AttributeName: SessionId
            AttributeType: S
        KeySchema:
          - AttributeName: SessionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 


plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin